### ISSUE TITLE
BucketRef ugliness, intra-component calls and maybe inconsistencies bug?

### ISSUE THREAD

**Issue by devmannic** [radixdlt/radixdlt-scrypto#102]
Using BucketRef is inconsistent and surprising.  I've tried to document a simple set of use cases when trying to return a BucketRef or something calculated from a BucketRef.

I think after creating these examples it makes the case for needing `vault.present(amount) -> VaultRef`
even for the normal case of not RESTRICTED tokens.

The RESTRICTED use case is discussed a bit here:  https://discord.com/channels/417762285172555786/765994894749597697/920722830558122084

See the related PR for the complete testable examples commenting each version and trying to document where things go wrong. -- dont' merge the PR, just a way to share the examples.

More details:

I don't know if this is complicated by how intra-component method calls are made, but maybe.  Do they have Radix Engine constraints checked with every function/method call, or only when the outermost call returns from Blueprint_main ?

Here's the problem:

These work...

```rust
        // works (assuming the tx includes a DropAllBucketRefs instruction)
        pub fn show(&self, amount: Decimal) -> BucketRef {
            self.sample_vault.take(amount).present()
        }

        // works, but very verbose, would much rather just use "show()"...but...
        pub fn have(&self, amount: Decimal) -> bool {
            let bucket = self.sample_vault.take(amount);
            let bucket_ref = bucket.present();
            let result = bucket_ref.amount() == amount;
            bucket_ref.drop(); // don't let the bucket ref dangle
            self.sample_vault.put(bucket); // don't let the bucket dangle
            result
        }
```
But this doesn't work

```rust
        // broken, but "expected" since the bucket becomes dangling.  this is pretty subtle compared to show()
        // why does .amount() make the bucket become dangling???
        pub fn have_b(&self, amount: Decimal) -> bool {
            let bucket_ref = self.sample_vault.take(amount).present();
            bucket_ref.amount() == amount
        }
```

See the PR for MANY more examples of attempts at resolving this.

**Comment by iamyulong** [comment]
Only the verbose option should work.

```
// works (assuming the tx includes a DropAllBucketRefs instruction)
pub fn show(&self, amount: Decimal) -> BucketRef {
    self.sample_vault.take(amount).present()
}
```
^ This smells like a regression bug.

**Comment by iamyulong** [comment]
> works, but very verbose, would much rather just use "show()"...but...

This is essentially how `authorize()` works.

**Comment by devmannic** [comment]
I wanted to add that I've now implemented `BucketRefOf<RES>` in `scrypto_statictypes` v0.3.0 and while doing so decided to implement the `Drop` trait.  This means it supports automatically dropping the wrapped BucketRef when the `BucketRefOf` goes out of scope, including when it gets sbor `Encode`d such as when it is a return value.  This is done correctly to ensure no double drops.  It makes for a much more ergonomic interface than remembering to manually `bucketref.drop()` and makes code that utilizes BucketRefs just generally cleaner.  See this larger `manyrefs` example  from `scrypto_statictypes` but generally allows for code changes like this: 

```rust
        pub fn check_amount_old(&self, auth: BucketRef, a: Decimal) -> bool {
            let br = self.mirror_old(auth);
            let r = br.amount() >= a;
            br.drop(); // required otherwise BucketRef is left dangling
            r
        }
        // BucketRefOf has Drop so this concise implementation is possible
        pub fn check_amount_new(&self, auth: BucketRefOf<T>, a: Decimal) -> bool {
            self.mirror_new(auth).amount() >= a
        }
```

@iamyulong I could port the same `Drop` code to the real `BucketRef` relatively easily without bringing along any of my static types / generic work if you 'd like to see this "auto drop" enhancement in Scrypto proper.  Thoughts?

Also, what's the plan on implementing `VaultRef` or extensions to `BucketRef` so they can be returned from a method call?  Currently this does not seem possible, so there is no way for a Component to show proof of a resource in the same way that BucketRef's are used by callers.  Or maybe that type of change is unnecessary and instead a more complex TransactionBuilder and ledger-side account component is needed?

**Comment by devmannic** [comment]
The implementation of Drop for BucketRef is probably quite similar to how I would implement it for Vault too to ensure they don't dangle as discussed in #87 .  I could probably fix both issues in the same PR if this is the agreed upon direction.
