### ISSUE TITLE
[bug?] Missing return `Bucket` for `Account::withdraw`?

### ISSUE THREAD

**Issue by devmannic** [radixdlt/radixdlt-scrypto#107]
This seems to be ignoring the `call_method` return value and missing the Bucket return type.

 https://github.com/radixdlt/radixdlt-scrypto/blob/a890ba796b4091f5aeccaff4bbeb49e6f288218c/scrypto/src/core/account.rs#L39

(I'm working on adding static checks to the Account methods in `scrypto_statictypes` and noticed this)

I'm guessing this means it may also be untested (since most of the existing code would use the TransactionBuilder::call_method(...,"withdraw",...) and the returned Bucket would just enter the transaction context, instead of having a component explicitly call `withdraw` on an `Account` component). - I bet it would just cause a `ResourceCheckFailure` but haven't tested it explicitly.

**Comment by iamyulong** [comment]
Thanks for raising this up. This is indeed a bug and a `Bucket` should be returned.

**Comment by gianlucardx** [comment]
Merged with PR #112
