### ISSUE TITLE
Change resource flags to a typed set to avoid misuse

### ISSUE THREAD

**Issue by devmannic** [radixdlt/radixdlt-scrypto#110]
https://github.com/radixdlt/radixdlt-scrypto/blob/b09e83585142e58c993694faa18930810fd5215b/scrypto/src/resource/resource_flags.rs#L1

The current implementation using an integer types is too easy to misuse.  There is no static type checking on the current types leading to runtime failures and confusion.  The flags are too easy to confuse between badge flags and resource flags mainly, and also using integers just to support the "OR" operation is not necessary.  Also IDEs cannot help with "intellisense" without unique types

References on Discord to issues with this:

1. https://discord.com/channels/417762285172555786/765994894749597697/916357719982755950
2. https://discord.com/channels/417762285172555786/765994894749597697/931483527764115468

There was another discussion I can't find right now.

A better alternative fitting the current API is simply replace the const flags with the use of the `flagset` crate, ideally 2 different types.  One that covers the badge permissions and the other that covers the resource features.  Using bit fields in Rust is notoriously tricky.  The `flagset` crate is one of the latest on the scene and seemingly one of the best to solve this, but there are many options.  Suggest a thorough look.

In addition to the bit flags, the API could be extended with functions like `.can_mint(badge)` and `.mintable()`  This is a little more verbose, but may have the advantage of better IDE detection.

**Comment by iamyulong** [comment]
Thanks for providing the feedback!

I agree that the current APIs are not ideal in the sense that they allow developers to create resource with arbitrary configuration, which may result in "unusable" resources, like a mintable resource with no minter.

One possible enhancement would be to check the configuration before committing it to system. This would generate a runtime error immediately when someone tries to create the resource.

I don't have much knowledge about `flagset`, but did compare enum with integer. I found it's much easier to compose flags by `OR`-ing integer flags, and the code is in general much readable (but with less IDE support as you mentioned).

**Comment by russellharvey** [comment]
Also we are looking at potentially addressing through namespacing the chance of making an error like using MAY_MINT (which is a permission) when you intended to use MINTABLE as a resource flag.

**Comment by 0xOmarA** [comment]
I'm closing this issue since the resource behavior is no longer defined through integer flags but is defined through the behavior methods when building the resource.
