### ISSUE TITLE
More technical documentation for transactions at runtime

### ISSUE THREAD

**Issue by devmannic** [radixdlt/radixdlt-scrypto#111]
I'd like to see a more thorough description with the technical details of what happens at runtime (preferably update this page too: https://docs.radixdlt.com/main/scrypto/system/runtime.html) in the following cases:

What exactly happens when a function or method calls another function or method on:
(A). the same package,
(B). a different package.

--- Looking at the simulator trace=true logs it seems like these are treated similarly and in both cases create a new context where Buckets and BucketRefs are validated but I would expect these Radix Engine constraints to only apply at the very end of a transaction.  I also would expect (A) to not have to go through the kernel to marshal arguments or state.  Maybe I'm misreading the logs though.

**Comment by devmannic** [comment]
I'll add that as things have changed a little for v0.4 and as I've learned more I want the docs even more now, even though my expectations may have changed. :)

For example I see that while marshalling args and state maybe wouldn't be needed some check for reentrancy and new wasm processes might still make sense, and there are the new auth checks.

I know docs may not be quite the priority at this point, but at least a little big picture flow from transaction manifest instruction all the way through to method call landing i think would be really useful.  Then as a bonus, a component calling another method in the same or different component/package.

**Comment by russellharvey** [comment]
Added to internal documentation backlog.
