### ISSUE TITLE
rror: BuildError(SchemaExtractionError(InvalidWasm(DeserializationError)))

### ISSUE THREAD

**Issue by tamfrancisco** [radixdlt/radixdlt-scrypto#1209]
When i publish my component i put

resim publish .

i get this error
rror: BuildError(SchemaExtractionError(InvalidWasm(DeserializationError)))

Can you help me please

**Comment by AuroraLantean** [comment]
Rust 1.70 can build Scrypto 0.10.0
See my similar error and its solution: https://github.com/radixdlt/radixdlt-scrypto/issues/1236

**Comment by dhedey** [comment]
Closing as this issue is now fixed on 0.10.0
