### ISSUE TITLE
incorrect schema extension in cmd_publish

### ISSUE THREAD

**Issue by bbarwik** [radixdlt/radixdlt-scrypto#1622]
In function `resim publish` when I try to publish wasm code, let's say `code.wasm` the command is searching for `code.schema`.
```
let code_path = self.path.clone();
let schema_path = code_path.with_extension("schema");
(code_path, schema_path)
```
However, when schema is generated it's saved with .rpd extension, not .schema (in function `pub fn build_package`).
So I think it should be `code_path.with_extension("rpd");` instead of `code_path.with_extension("schema");`

**Comment by iamyulong** [comment]
Resolved.
