### ISSUE TITLE
Need a "VaultRef"?  ...consequences of lost `drop_all_bucket_refs` on the `TransactionBuilder` or something else?

### ISSUE THREAD

**Issue by devmannic** [radixdlt/radixdlt-scrypto#165]
I'm shoving 2 related problems into this one issue.  First is that without `drop_all_bucket_refs` i can't successfully run an integration test which I could do in v0.2.0.  Second, even if I could drop the BucketRef propertly in at least one of those tests, I think I was making use of a bug in the RE described in #102 and now that the bug is fixed I don't know how to correctly implement the idea.

First, why was `drop_all_bucket_refs` removed?  Is there an alternative?  I see `drop_bucket_ref` but I've tried using it but don't know how to reference the correct BucketRef to drop which is a result from a previous instruction.  I've tried to manually create the Rid from the integer value I see printed in the log but that didnt' work either.

And the more complicated issue:

I want a method on my component that returns proof of the existence of an asset (in a Vault).  I thought having such a feature would be useful in various DeFi algorthms, particularly when composing calls across components in a single transaction it would limit inaccuracy and some types of bugs/attacks and fail sooner then downstream if/when actually `take`ing.

The concrete use case is  `get_sell_quote` in the bonding curve amm merged into `community-scypto`.  Here's the version that works with v0.2.0: 

```rust
        pub fn get_sell_quote(&self, continuous_amount: Decimal) -> BucketRef {
            // This variant returns a BucketRef for proof.  Only possible with sell because
            // for buying, we can't return "proof" because the amount isn't minted yet

            // use the generated stubs for calling methods on the Component (kind of like a virtual call aka dynamic dispatch, but it happens via the kernel)
            let curve: crate::bonding_curve::BondingCurve = self.bonding_curve.clone().into();
            // calculate the amount that would be returned
            let return_amount = curve.get_return_amount(continuous_amount, self.reserve.amount(), self.continuous.resource_def().total_supply());
            // return a placeholder for the amount as proof we have it in reserve
            let bucket = self.reserve.take(return_amount);
            bucket.present() // return proof of amount, but don't give it away
        }
```

You can look in the integration tests for how it's tested.  The integration tests use scrypto-unit which makes it a little harder to see what's going on, but it amounts to:

```rust
.call_method(..., "get_sell_quote", ...)
.drop_all_bucket_refs()
.deposit_all_buckets(account)
```

I can't actually introspect anything about what is returned, but at least I can see the tx succeeds.

But, on v0.3.0 it does:

```rust
.call_method(...)
.call_method_with_all_resources(account, "deposit_batch")
```

and the transaction fails with `BucketRefNotAllowed`

I see in the implementation that `call_method_with_all_resources` actually does `drop_all_bucket_refs()` under the covers in `process.rs`  I'm not sure if this is helping me, hurting, or doesn't matter...

What's the best way to do this in v0.3.0?

**Comment by iamyulong** [comment]
> why was `drop_all_bucket_refs` removed

At the transaction layer, all created `BucketRef` (`Proof` in future versions) should be passed to a component or blueprint. With `v0.3`, the callee will automatically drop these `BucketRef`s, so there is no need to _drop all_ bucket refs in transaction.

The `drop_bucket_ref` is needed only when you've created a `BucketRef` but want to cancel it.

**Comment by iamyulong** [comment]
Alternatively, `call_method_with_all_resources` will cancel all bucket refs

**Comment by iamyulong** [comment]
Re `BucketRefNotAllowed`, are you returning a `BucketRef`? This is not allowed since v0.3.

**Comment by devmannic** [comment]
Thanks, that information is consistent with what I'm seeing and makes sense.  But: 

> Re BucketRefNotAllowed, are you returning a BucketRef? This is not allowed since v0.3.

This is really the issue.  If I build a method that returns a `BucketRef` with the intent that another component will use it there is no way to actually test it within a transaction without also creating some mock test component to consume it.  Is there some way existing or planned to enable unit or integration testing of methods that return `BucketRef`s without doing that?  Or maybe an easier pattern for test-only components is all I really need.  Currently I don't see any great options.

**Comment by iamyulong** [comment]
`CLEAR_AUTH_ZONE` has been added on `develop` branch, which could be used for clearing proofs.
