### ISSUE TITLE
Mind sharing which segment of codes prevents naked values of unauthorized types, e.g. `Resource` still existing when the function scope ends.

### ISSUE THREAD

**Issue by jymchng** [radixdlt/radixdlt-scrypto#1651]
Hi

I am an engineer and I am interested in the codes that give rise to the behaviour I mentioned in the title. I tried searching your codebase for this but was unable to find any.

Anyway, showing that this behaviour is guaranteed at the code level is something that can convince more developers to work on Radix.

**Comment by dhedey** [comment]
Hi @jymchng it's the heap / stack part of the [kernel](https://radix-engine-docs.radixdlt.com/architecture/kernel/index.html).

A call frames owns ReNodes (of which a Bucket is an ReNode) and on returning from a call frame, it can't still be holding any nodes - this is checked here: https://github.com/radixdlt/radixdlt-scrypto/blob/7dbe606bac3d2661a47c30a43dafb5016074f130/radix-engine/src/kernel/kernel.rs#L1246

The correctness that Bucket and Vault maintain resource balances during the lifecycle of buckets can be checked [inside the Resource native package](https://github.com/radixdlt/radixdlt-scrypto/tree/main/radix-engine/src/blueprints/resource).
