### ISSUE TITLE
Security audit of ed25519-dalek

### ISSUE THREAD

**Issue by Kansuler** [radixdlt/radixdlt-scrypto#1835]
There seem to be two security issues that are patched in future versions of `ed25519-dalek` and sub dependency `curve25519-dalek`.

The list of issues due to `ed25519-dalek@1.0.1` are
- [RUSTSEC-2022-0093](https://rustsec.org/advisories/RUSTSEC-2022-0093)
- [RUSTSEC-2024-0344](https://rustsec.org/advisories/RUSTSEC-2024-0344)

The issues are resolved in the latest version of `ed25519-dalek@2.1.1`.

**Comment by dhedey** [comment]
Many thanks @Kansuler for the report.

We have previously investigated [RUSTSEC-2022-0093](https://rustsec.org/advisories/RUSTSEC-2022-0093) and confirmed that the usage of `ed25519-dalek@1.0.1` in code was not a problem for this issue. More specifically, we wrap the private keys in `Ed25519PrivateKey` which ensures that the `secret` and `public` properties of keypair are aligned.

We will need to investigate [RUSTSEC-2024-0344](https://rustsec.org/advisories/RUSTSEC-2024-0344), but it looks likely the code is affected, and we will look into fixing this.

Whilst we generally advise that integrators use their own signing libraries, we appreciate that some may choose to use those built into the engine test framework, so will look at whether we can update to offset the risk of timing attacks.

**Comment by dhedey** [comment]
Will be fixed in Cuttlefish courtesy of https://github.com/radixdlt/radixdlt-scrypto/pull/1933
