### ISSUE TITLE
Deterministic WASM build

### ISSUE THREAD

**Issue by iamyulong** [radixdlt/radixdlt-scrypto#19]
With deterministic WASM build, one can verify if the published WASM binary is produced from a specific Scrypto source code and compiler toolchain.

Parity team has been using Docker image to produce deterministic outputs. According to [their blog post](https://dev.to/gnunicorn/hunting-down-a-non-determinism-bug-in-our-rust-wasm-build-4fk1),

> Wasm is overall a great invention providing a thin multi-plattform abstraction over the machine language target. Thus the wasm output from a compiler can easily be translated into the actual machine code needed for execution. However, WebAssemblz is not human readable, which makes it hard to audit for the people who should vote upon the chain upgrade. Upgrading a blockchain state transition function can't be taken back, so voting on an opaque block is not particularly instilling confidence in its users.
>
> The way we approach this problem is through "deterministic builds". The rust compiler itself does not, as of now, guarantee that builds are deterministic – meaning that compiling the same code twice will yield the same resulting binary. However, Parity has managed to solve this problem for our code. So at least within the same environment (OS, Compiler, libs installed) it is reasonably deterministic for a set of targets to be consistent and wasm32-unknown-unknown is among them. This allows us to produce a docker-image (and its build description) confirming that the Rust source files indeed result in the binary blob proposed as the next chain runtime. Using the Docker image, auditors can look at the source code directly and do not have to wade through the wasm32 bytecode.

We need to check if similar approach can be applied to Scrypto.

**Comment by russellharvey** [comment]
Moved to internal tracking
