### ISSUE TITLE
Making `LocalComponent`s aware of blueprint methods and functions for auth

### ISSUE THREAD

**Issue by 0xOmarA** [radixdlt/radixdlt-scrypto#230]
Hi, I've been looking through the v0.4.0 and I'm pretty excited about the changes coming!

I like the new change where the `ResourceMethod` enum was introduced for the resource auth as works better than strings in this case. 

At the current moment of time, the `LocalComponent` is unaware of the functions and methods which exist on the blueprint, leading to the following scenarios being possible:
```rust
Self{}
    .instantiate()
    .auth("method which does not exist", auth!(allow_all))
    .globalize()

Self{}
    .instantiate()
    .auth("1234568!!!!!", auth!(allow_all))
    .globalize()

Self{}
    .instantiate()
    .auth("method which actually exists + small typo", auth!(allow_all))
    .globalize()

Self{}
    .instantiate()
    // .auth("accidentally commented out auth call for a method which I wanted to add auth for", auth!(allow_all))
    .globalize()
```

While the above scenarios do not lead the code to break or anything, it could make Scrypto code harder to debug for people who are new to the space and new to Scrypto. 

Could the `LocalComponent` be made aware of the functions and methods that exist on the underlying blueprint such that when `auth` is called on a `LocalComponent` the `method_name` is checked to ensure that it's indeed a valid method that exists on the blueprint, not a typo, or a method that no longer exists due to a name change, etc... ? 

For added convenience, perhaps the `LocalComponent.globalize` method could also check to ensure that all methods had authorization assigned to them. Perhaps the `LocalComponent.globalize` could panic or give a warning message when a public method is found without any authorization rule as that is probably something that the developer forgot to add.

**Comment by devmannic** [comment]
1000% agree with this.  Been watching this evolve too and really think these extra checks proposed should be a priority.  As it stands there's lots of rain for error and security retirement errors too

**Comment by devmannic** [comment]
I would also like to see a declarative way to add auth near the methods too via annoyations if those are just used as defaults

**Comment by devmannic** [comment]
I also think generally speaking a "fail closed" system is better and safer.  Ie. No auth specified means only callable by self, equivalent to non pub.  I'm not sure if that is how things behave now or not.

**Comment by 0xOmarA** [comment]
Totally agree with you @devmannic, syntax like:
```rust
#[auth(owner_badge | admin_badge & user_badge)]
pub fn method(&self) -> Bucket {}
```

Could be really nice, I'm not entirely certain if such syntax would be possible with the new auth system that supports logical operations of badges or not. But I think that something like this would be really nice.

**Comment by talekhinezh** [comment]
@0xOmarA Good points!

> Could the LocalComponent be made aware of the functions and methods that exist on the underlying blueprint such that when auth is called on a LocalComponent the method_name is checked to ensure that it's indeed a valid method that exists on the blueprint, not a typo, or a method that no longer exists due to a name change, etc... ?

Yes, this is definitely planned in the works. A prereq to this is storing all methods for a given blueprint which isn't implemented yet. Furthermore, hoping that we can integrate such checks during compile time if e.g. `.auth()` is being set in the same blueprint.

> For added convenience, perhaps the LocalComponent.globalize method could also check to ensure that all methods had authorization assigned to them. Perhaps the LocalComponent.globalize could panic or give a warning message when a public method is found without any authorization rule as that is probably something that the developer forgot to add.

I don't think a component creator will always necessarily want all methods made accessible. This is part of the power of having a separate "interface"/"auth" layer between code and caller. A simple example is resource. where we don't want to allow minting for example.

**Comment by talekhinezh** [comment]
@devmannic 
> I would also like to see a declarative way to add auth near the methods too via annotations even if those are just used as defaults

I think when dealing with authorization it's much cleaner to have all auth in one place rather than being able to declare in multiple places, as then questions like which rule takes precedence can be avoided. Also dislike the idea of "default" auth as it adds a layer of indirection regarding auth which I think should be fully explicit up front so that it's crystal clear what the rules are.

**Comment by talekhinezh** [comment]
@devmannic 
> I also think generally speaking a "fail closed" system is better and safer. Ie. No auth specified means only callable by self, equivalent to non pub. I'm not sure if that is how things behave now or not.

Totally agree and this is how it's been implemented.

**Comment by 0xOmarA** [comment]
@talekhinezh Thank you so much for your quick response!

> Yes, this is definitely planned in the works. A prereq to this is storing all methods for a given blueprint which isn't implemented yet. Furthermore, hoping that we can integrate such checks during compile time if e.g. .auth() is being set in the same blueprint.

I'm very happy to hear that this is something the team is hoping to do as I believe this to be important. A compile time check would be incredibly useful for the component authorizations.

> I don't think a component creator will always necessarily want all methods made accessible. This is part of the power of having a separate "interface"/"auth" layer between code and caller. A simple example is resource. where we don't want to allow minting for example.

I agree with you that the component creator would not want all methods to be accessible, but what about public methods specifically? To me I feel like that when the developer has declared a method to be public and forgot to specify any authorization for it then this is done by mistake and not intentionally.

As an example:

```rust
use scrypto::prelude::*

blueprint! {
    struct Human {}

    impl Human {
        pub fn new_human() -> ComponentAddress {
            Self {}
                .instantiate()
                .globalize()
        }

        pub fn walk(&self) {}
    }
}
```

In this example, the method `walk` is a public method. However, no auth is provided for the method when creating the component so the `walk` method is not exactly "public" after all since it can only be accessed from within the component. Since the developer of the component specified `walk` as a public method but forgot to add any `auth` for it then we can assume that this was done by mistake and perhaps a warning could be shown.

**Comment by talekhinezh** [comment]
Perhaps its the fact that `pub` is attached to the `walk` method that makes this confusing. The concept of "public methods" is mostly be an interface/auth issue decided by the component creator rather than the blueprint creator.

I wouldn't consider missing some `pub` methods a mistake for example:

```rust
use scrypto::prelude::*

blueprint! {
    struct Human {}

    impl Human {
        pub fn walking_human() -> ComponentAddress {
            Self {}
                .instantiate()
                .auth("walk", auth!(allow_all))
                .globalize()
        }
        
        pub fn flying_human() -> ComponentAddress {
            Self {}
                .instantiate()
                .auth("walk", auth!(allow_all))
                .auth("fly", auth!(allow_all))
                .globalize()
        }

        pub fn walk(&self) {}
        
        pub fn fly(&self) {}
    }
}
```

**Comment by 0xOmarA** [comment]
@talekhinezh Haha I love the example and it makes sense! I can see now why not all public methods need to have an auth.

**Comment by talekhinezh** [comment]
Heh glad that helped! Maybe a helpful analogy from the web world is the blueprint code is web server code and the auth/interface layer is nginx. Depending on your use case you may want to change nginx configuration independently from your core logic for your instantiation.

**Comment by r001** [comment]
I think this declarative way makes a lot of sense as devs who use a given
method should know when they look at the function name if auth is
involved in it or not. I also agree that there should be only one way
not to confuse anyone.


The 04/09/2022 11:24, Joshua Primero wrote:
> @devmannic 
> > I would also like to see a declarative way to add auth near the methods too via annotations even if those are just used as defaults
> 
> I think when dealing with authorization it's much cleaner to have all auth in one place rather than being able to declare in multiple places, as then questions like which rule takes precedence can be avoided. Also dislike the idea of "default" auth as it adds a layer of indirection regarding auth which I think should be fully explicit up front so that it's crystal clear what the rules are.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/radixdlt/radixdlt-scrypto/issues/230#issuecomment-1094101379
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>

-- 
Robert Horvath

**Comment by talekhinezh** [comment]
@devmannic No problem! It's perhaps been unclear because even on our side we're working on figuring out the best interface to this complicated configuration which like you mention is "all tied up with each other". Not to mention how all of this ties up with future features (such as royalties)

> Is there actually a way for a caller to instantiate and globalize a blueprint defined in a separate package? Or what about another blueprint in the same package?

Not instantiation. Instantiation is only allowed in the package which defines the blueprint. Globalization of components will be allowed in other components, as well as attaching auth layer(s) to an instantiated component.

> So with that in mind my thinking is that having an auth declaration directly on the method itself in the form of an annotation (or extra variable as was done previously) is useful because it provides a way for the originating blueprint writer to make some guarantee about the auth for every instantiation of a component they design no matter who instantiates it or how.what

This would still be possible without using some form of annotation. For example (using the latest interface):

```rust
blueprint! {
    struct MyThing {}

    impl MyThing {
        pub fn new() -> Component {
          let auth = Authorization::new()
              .method("my_protected_method", AUTH_A)
              .default(method_auth!(allow_all))
              
          Self { }
            .instantiate()
            .auth(auth)
        }
    }
```

```rust
let my_auth = Authorization::new()
  .method("my_protected_method", AUTH_B)
  .method("another_method", AUTH_C)
  .default(method_auth!(deny_all));
  
let component_address = MyThing::new().auth(my_auth).globalize();
```
The component now has the combined authrules:
- `my_protected_method`: AUTH_A && AUTH_B
- `another_method`: AUTH_C
- all other methods: DENY

Curious to hear your thoughts!

**Comment by devmannic** [comment]
@talekhinezh Sorry I spaced out on replying to this.  I initially read it on mobile and thought, "well that all looks perfect!" :)

"Not Instanation" is exactly what I meant to be able to ensure some baseline auth, exactly as you described in your example.  So yeah, this looks really good to me.

I think another reason I initially balked at this implementation is the use of method name strings.  But I think I remember seeing some discussion of that maybe changing?  I'd much rather see `MyThing::my_protected_method` used instead of that string (which could just be a const) or even better something like `MyThing::Authorization::new().auth_rule_for::my_protected_method(AUTH_A)` where the underlying enum and associated type could be generated with the blueprint macro.  This would get compile time checks for these.

**Comment by talekhinezh** [comment]
@devmannic No worries! And yes, we'll definitely be swapping out the method name strings with something compiler enforceable, probably using the blueprint macro to generate method enums like you mention. There are quite a few steps to get to that point though and it probably won't make it into v0.4.

**Comment by devmannic** [comment]
> ... it probably won't make it into v0.4.

No surprise there.  Can see all the work gone into v0.4 already.  Glad to hear it's on the radar!

**Comment by russellharvey** [comment]
Fixed now.
