### ISSUE TITLE
Cannot input Proof or Bucket wrapped inside Option type on transaction manifest

### ISSUE THREAD

**Issue by unghuuduc** [radixdlt/radixdlt-scrypto#366]
Cannot input Proof or Bucket wrapped inside Option type on transaction manifest, here is my whole test code
![image](https://user-images.githubusercontent.com/55659332/175334080-c94b0baa-1916-4484-968a-a0c00937b4aa.png)

Here is the transaction manifest:
![image](https://user-images.githubusercontent.com/55659332/175334509-daacaf46-8488-43cd-81bd-8e369cdd50f6.png)

Here is the error
![image](https://user-images.githubusercontent.com/55659332/175334559-1dc7f16d-9a1d-48fc-a54c-e9c281c28fb5.png)

The error trace back to this [link](https://github.com/radixdlt/radixdlt-scrypto/blob/main/scrypto/src/values.rs#:~:text=.unwrap()%3B,-if%20let%20Value)

Seem like there is some problem with Option value type on the transaction manifest. 
When I define another enum:

`#[derive(TypeId, Encode, Decode, Describe)]
pub enum OptionProof {
    None,
    Some(Proof)
}`

It worked fine.

**Comment by 0xOmarA** [comment]
Hey Peter, we have identified the issue behind this: apparently `Option`s and `Results` were not being treated as enums which causes this issue. I have made a PR fixing this issue so you can expect to see it fixed with v0.5.0.
