### ISSUE TITLE
Disallow component re-entrance

### ISSUE THREAD

**Issue by iamyulong** [radixdlt/radixdlt-scrypto#45]
When a method is called, the component state is loaded into memory. All state changes are cached and flushed at the end of the invocation.

This may cause unexpected behaviour when there is a re-entrance. The state changes by child process are overwritten by parent process.

**Comment by devmannic** [comment]
@iamyulong I see that reentrance is explicitly blocked now in v0.4.  Does that mean you can close this or is there more to do to expand on when it may actually be allowed (or when else it would be blocked) ?

**Comment by iamyulong** [comment]
Yes, we can close this now.
