### ISSUE TITLE
Feature request : Implementation of block number or timestamp

### ISSUE THREAD

**Issue by tomashla** [radixdlt/radixdlt-scrypto#450]
Hello,
I would like to request a feature of timestamps or block numbers / blockchain height in Scrypto.
This feature would allow much more precise time targetting. It would further improve independence of radix developers on external data sources as well as unlock lot of new use cases of Scrypto.
Thank you for considering my request.

**Comment by a137x** [comment]
Work in progress:
https://discord.com/channels/417762285172555786/765994894749597697/1030184205063290900

**Comment by 0xOmarA** [comment]
I will be closing this since timestamps have already been implemented in Scrypto v0.7.0 as Beem's pointed out. Here is some additional info on this: https://docs-babylon.radixdlt.com/main/scrypto/release_notes/migrating_from_0.6_to_0.7.html#_added_access_to_real_world_time

**Comment by tomashla** [comment]
Thank you, Omar, I thought it was closed as soon as you implemented it. Sorry for bothering you and not closing it myself.
