### ISSUE TITLE
Documentation Request: Support for Homebrew-installed Rust?

### ISSUE THREAD

**Issue by brandondrew** [radixdlt/radixdlt-scrypto#491]
Is Rust installed by Homebrew sufficient for Scrypto?

If yes, it would be very helpful to note in the README how to handle step 3.  (There's no `rustup` available to me with my installation of Rust 1.63.0.)  

If no, it would be very helpful to note that in the README.  

In the meantime, I'll simply uninstall Homebrew's Rust and install it from rustup.rs, but I thought I would post this issue in the hopes of helping to improve the documentation for the next person.

**Comment by russellharvey** [comment]
Any Rust installation works, keeping instructions to single path using rustup.
