### ISSUE TITLE
To `mut` or not to `mut`

### ISSUE THREAD

**Issue by murraco** [radixdlt/radixdlt-scrypto#52]
Hello!

Nice work on Scrypto.

I noticed in the [radixswap](https://github.com/radixdlt/radixdlt-scrypto/blob/main/examples/defi/radiswap/src/lib.rs#L66) example that the reference to `self` in the `add_liquidity`, `remove_liquidity` and `swap` methods is not mutable, is this a bug or am I missing something?

**Comment by iamyulong** [comment]
Thank you @murraco for reporting this issue!

All Scrypto objects, e.g. `Vault`, `Bucket`, `ResourceDef` and `LazyMap`, currently use the [interior mutability pattern](https://doc.rust-lang.org/book/ch15-05-interior-mutability.html).

It makes it easier to manipulate objects without compile-time borrowing rule check, but is less intuitive. 

We're considering adding mutability syntax to Scrypto objects to reinforce Rust ownership paradigm. 

Everyone are welcome to leave comments on this issue.

**Comment by kroggen** [comment]
If we want the language to be the easiest with lower learning curve and higher adoption, then we should make it simple. Removing the need for this `mut` is one less thing to learn
