### ISSUE TITLE
Add colored output to the following macros `info!()` , `warn!()` and `error!()`

### ISSUE THREAD

**Issue by plymth** [radixdlt/radixdlt-scrypto#521]
When running scrypto tests with `scrypto test -- --nocapture` due to the amount of output displayed it can be hard to track some of the info messages you have logged. Could we leverage the `colored` crate to add colored  output to the following macros:

`info!()` -> blue
`warn!()` -> yellow
`error!()` -> red

I think it might be possible to do something like this:

```rust
use colored::Colorize;
...
macro_rules! info {
    ($($args: expr),+) => {{
        ::scrypto::core::Logger::log(scrypto::core::Level::Info.blue(), ::sbor::rust::format!($($args),+).blue());
    }};
}

```

**Comment by beemdvp** [comment]
By convention, `info` usually either green or default terminal colour

**Comment by plymth** [comment]
> By convention, `info` usually either green or default terminal colour

It was the default white color that was causing the readability issues, but sure green or blue is fine with me 😁  .

**Comment by russellharvey** [comment]
Will add it internal tracking of desired resim features.
