### ISSUE TITLE
Test: new_token_fixed should not be a valid badge

### ISSUE THREAD

**Issue by kroggen** [radixdlt/radixdlt-scrypto#53]
I saw that in the video the radiswap example worked even using the `new_token_fixed()` instead of `new_badge_fixed()`

Could this lead to some undesired behaviors, like a breach for attacks?

It could have a test that should fail if `new_token_fixed()` is used to create a badge

(correct me if I am wrong)

**Comment by iamyulong** [comment]
As of now, both badges and tokens are backed by resource. 

The only difference is granularity:
- Tokens have granularity of 1 (which is 10^-18)
- Badges have granularity of 18 (which is 1.0)

When a BucketRef to a badge is presented, the component checks both resource definition address and the quantity associated. From a security perspective, it can cause problem if granularity matters, for which we need a few specific usecases.

**Comment by kroggen** [comment]
In my opinion ResourceDef for badge and tokens should have a "type" field to differ them, so when using `resim show ...` it would return the type of resource.

And the engine itself can use this type to differ them.

**Comment by iamyulong** [comment]
> So if we present any ResourceDef it will be able to mint and burn?

No, to mint or bun, one need the minter badge.

> What if the user sends a token instead of a proper badge, and component uses the given token to mint or burn... Would it work?

When badge is used for authorisation, only a `BucketRef` is passed. The component has read-only access and does not own it.

> In another words, why it worked on the example? Why did it mint tokens using another token instead of a badge?

The blueprint defines the resource address (type) required. If token is used, token BucketRef is passed; if badge is used, badge BucketRef is passed. Both work, but it's recommended to use badge for authorisation.

> In my opinion ResourceDef for badge and tokens should have a "type" field to differ them, so when using resim show ... it would return the type of resource.

I do like the "type" idea; in fact, I'm already introducing it when implementing NFT.

**Comment by kroggen** [comment]
OK, I am starting to understand this now. When minting or burning, the system only checks something like a unique address (or hash) that identify that resource that was created with the intention to be a badge or authorizer.

Anyway, I still think that it would be useful for the system to detect if what is presented is anything else, just to detect developer misuse. Maybe not a big deal though

Thanks for the patience!

**Comment by kroggen** [comment]
If the above change is implemented, the `new_token_mutable()` function could be used like this:

```rust
  .new_token_mutable(minter_badge);
```
Instead of

```rust
  .new_token_mutable(minter_badge.resource_def());
```
In this way the called function can check the type of the passed resource, and it is also simpler for use

**Comment by iamyulong** [comment]
If `minter_badge` is a bucket, I think `.new_token_mutable(minter_badge.resource_def());` is the right way. 

When creating a resource with mutable supply, we need to provide the minter badge resource definition address as a parameter.

**Comment by kroggen** [comment]
Yes, I know.

But I suppose that the `new_token_mutable` function could check the object type and then retrieve the resource definition from the passed in badge object (correct me if I am wrong)

Something like:

```rust
pub fn new_token_mutable(... badge){
  if badge.type != "badge" ...  // fail here
  let resource_def = badge.resource_def();
  ...
}
```

**Comment by kroggen** [comment]
Anyway, maybe this is not so important. It is just weird (for me) that the engine accepts any address as the authorizer. Not a big deal

**Comment by iamyulong** [comment]
With the newest resource model, we no longer categorise resource as token, badge and NFT.

Instead, there are only fungible resource and non-fungible resource. Badge (resource used for authorisation) can be both fungible and non-fungible, depending specific use case.

 _Not merged into main yet._

**Comment by kroggen** [comment]
Being able to have non-fungible badges with specific metadata may be useful.

But I still think that the API should be easier to use...

```rust
            let lp_mint_badge = ResourceBuilder::new_fungible(18)
                .metadata("name", "LP Token Mint Auth")
                .initial_supply_fungible(1);
```

Why `fungible` appears twice? If it already informed that it is creating a fungible resource, then function could be called `initial_supply()`.

What is the `18`?

Also, I still think that when creating a badge we should use the word `badge` somewhere and that this should be stored in the resource as a sub-type, and the system could check if the resource is a badge. This is to avoid dev errors. Unless there is a clear reason to not do that...

I would prefer something like this:

```rust
            let lp_mint_badge = ResourceBuilder::new_badge(FUNGIBLE)
                .metadata("name", "LP Token Mint Auth")
                .initial_supply(1);
```

**Comment by kroggen** [comment]
I still think that badge, token and NFT are easier to understand for the end users/developers. Fungible and non-fungible are base resources constructions from which they derive.

I think that `new_fungible()` should be an internal function, and expose `new_badge()`, `new_token()` and `new_nft()`

I also think that you guys should make a pool on Discord about this before merging

**Comment by kroggen** [comment]
Regarding this:

```rust
            let lp_resource_def = ResourceBuilder::new_fungible(0)
                .metadata("symbol", lp_symbol)
                .metadata("name", lp_name)
                .metadata("url", lp_url)
                .flags(MINTABLE | BURNABLE)
                .badge(lp_mint_badge.resource_def(), MAY_MINT | MAY_BURN)
                .no_initial_supply();
```

If the `.badge()` call is already informing that the token can be minted and burned, then the `.flags()` call with similar keywords can be omitted. There is no need for redundancy

It could also use `new_token(FUNGIBLE)`:

```rust
            let lp_resource_def = ResourceBuilder::new_token(FUNGIBLE)
                .metadata("symbol", lp_symbol)
                .metadata("name", lp_name)
                .metadata("url", lp_url)
                .badge(lp_mint_badge.resource_def(), MAY_MINT | MAY_BURN)
                .no_initial_supply();
```

Way better

**Comment by devmannic** [comment]
@kroggen  I agree with the sentament that simplier is better and where possible there should be some wrapper APIs for the ResourceBuilder for common cases.  100% want that too.  It's a little too verbose for my liking too.  But it does enable more options and is consistent.  Both important.  I'd rather see a secondary API for typical patters and this API as stated for complex token types.

With that said, it looks like your last example is mixing up the semantics a little, or at least oversimplifying.  The `MINTABLE | BURNABLE` applies to the resource while the `badge` authorizes the badge resource def to MINT and BURN.  There could be other badges with different permissions for example.  There might be default cases where you want one to imply the other and shouldn't have to write things twice, but that type of complexity can get ugly quick.

**Comment by iamyulong** [comment]
> Why fungible appears twice? If it already informed that it is creating a fungible resource, then function could be called initial_supply().

This is mainly because Rust doesn't allow function overloading. Will explore if there is a better approach.

>  Why fungible appears twice? If it already informed that it is creating a fungible resource, then function could be called initial_supply(). What is the 18?

We're going to replace `granularity` with `divisibility`, which could be `[0, 18]`.  It essentially means the number of decimal places after the point.

**Comment by kroggen** [comment]
@devmannic 

> With that said, it looks like your last example is mixing up the semantics a little, or at least oversimplifying. The MINTABLE | BURNABLE applies to the resource while the badge authorizes the badge resource def to MINT and BURN. There could be other badges with different permissions for example. There might be default cases where you want one to imply the other and shouldn't have to write things twice, but that type of complexity can get ugly quick.

I understood that the resource can have badges with different rights, but if it has at least one with MINT and BURN rights, then the `.badge()` function can internally call the `.flags()` function informing that, to avoid the repetition for the end user/developer.

The `flags()` function can still be available if the user wants to set other flags, but not needed to be used in the above case.

**Comment by kroggen** [comment]
Should the badges have the granularity/divisibility of 18 by default?
Then we would not need to inform it when creating a badge.

Should it be the same for NFTs?

By the way, instead of "by default" they could be enforced (not giving option) and only allow setting the divisibility for fungible tokens, either as an argument or using  a `.divisibility()` function.

Also, if we would have a `new_token()` and `new_nft()`, then the `FUNGIBLE` in `new_token(FUNGIBLE)` is not required

**Comment by kroggen** [comment]
Maybe rename `initial_supply_non_fungible()` to `initial_nft_supply()` (or whatever)

And let `initial_supply()` for fungibles

Do people usually use the word `supply` for NFTs?

Why not ask for ideas on Discord?

**Comment by kroggen** [comment]
And we could have a function `new_badge()` on the `ResourceBuilder` that internally calls the related function

Something like this:

```rust
pub fn new_badge(type: SomeEnum) -> Xxx {
  if type == FUNGIBLE {
    Self::new_fungible(DIVISIBILITY_NONE)
  } else if type == NON_FUNGIBLE {
    Self::new_non_fungible()
  } else {
    assert!(false, "invalid resource type");
  }
}
```

So we could use:

```rust
            let my_badge = ResourceBuilder::new_badge(FUNGIBLE)
                .metadata("name", "My Fungible Badge")
                .initial_supply(1);
```

And

```rust
            let my_badge = ResourceBuilder::new_badge(NON_FUNGIBLE)
                .metadata("name", "My Non-Fungible Badge")
                .initial_nft_supply([
                  ...
                ]);
```

**Comment by kroggen** [comment]
The above `new_badge()` function can also be used to mark the created resource as a badge

By the way, this is the original reason of this issue: to **differ** badges from other tokens in some way, so the engine can treat them as such when needed. And this requirement may not exist now but it can come in the future. Better be prepared

Maybe this mark on them can help when creating a BucketRef?

Anyway, even for wallets, etc. It is good to have a distinction between normal tokens and badges

**Comment by russellharvey** [comment]
Obsolete
