### ISSUE TITLE
Make AccessRules.default an Option and initialize it to None

### ISSUE THREAD

**Issue by backyard-coder** [radixdlt/radixdlt-scrypto#532]
At the moment struct `AccessRule` is defined as follows:
```rust
pub struct AccessRules {
    method_auth: HashMap<String, AccessRule>,
    default_auth: AccessRule,
}

impl AccessRules {
    pub fn new() -> Self {
        Self {
            method_auth: HashMap::new(),
            default_auth: AccessRule::DenyAll,
        }
    }
    ...
}
```
In fn `new` the struct is initiated with a default rule of `AccessRule::DenyAll`. This is probably well intended, so as to protect the component from unwanted access, but is ultimately dangerous. It is easy to miss a method in the access rule definition, which results in that method being non-callable forever. Using `AccessRule::AllowAll` as the default is of course no good solution either.

It would be better to make the default an `Option` initialized to `None`. If the developer does not provide a default, throw an error in case there are methods without an access rule. This way it would be much harder to accidentally miss an access check for a method and end up with an unwanted default that may break the component's functionality.

Proposed change:
```rust
pub struct AccessRules {
    method_auth: HashMap<String, AccessRule>,
    default_auth: Option<AccessRule>,
}

impl AccessRules {
    pub fn new() -> Self {
        Self {
            method_auth: HashMap::new(),
            default_auth: None,
        }
    }
    ...
}
```

**Comment by russellharvey** [comment]
Obsolete, desired goal met through new model.
