### ISSUE TITLE
Use variables that represent fractions

### ISSUE THREAD

**Issue by kroggen** [radixdlt/radixdlt-scrypto#55]
Maybe some day Scrypto could use variables that represent fractions (rational numbers) with numerator and denominator, like [num-rational](https://github.com/rust-num/num-rational/blob/master/src/lib.rs)

In this way we could use the simple syntax (easier to understand) without concerning about rounding issues

I don't know if there is any smart contract platform that supports this, and as Radix is focused on DeFi it would be a good fit

In this case the radiswap code could be kept mostly as it is, as long as the returned type in math operations would be the rational/fraction class, example:

```rust
let share = lp_tokens.amount() / self.lp_resource_def.supply();
```

In this case `share` would be of faction/rational class, and when used in multiplications or divisions, it would avoid losses

For the above to work the `amount()` and `supply()` should return `fraction` instead of `Decimal`, and then the division operator will be dealt by the class

The downside is the overhead, the library is not small and the computation is higher, probably making the cost higher too

Let's see what other devs think about this

_Originally posted by @kroggen in https://github.com/radixdlt/radixdlt-scrypto/issues/50#issuecomment-971177195_

**Comment by iamyulong** [comment]
Thank you @kroggen for making the suggestion. I'm not able to look into this immediately, but will keep the ticket open for further investigation.

**Comment by russellharvey** [comment]
Moved to internal desired type tracker
