### ISSUE TITLE
Avoid the borrow() function when possible

### ISSUE THREAD

**Issue by kroggen** [radixdlt/radixdlt-scrypto#56]
Original code:

```rust
  let tokens = token_def.mint(amount, minter_badge.borrow());
```

The above code uses the `borrow()` function that has another meaning in finance, so here are some suggestions on how to handle the presentation of badges when necessary

**Option 1:**

```rust
  let tokens = token_def.mint(amount, minter_badge);
```

Just pass the badge directly as the parameter, and let the functions that receive them to handle them properly

**Option 2:**

```rust
  let tokens = token_def.mint(amount, minter_badge.present());
```

Create another function that calls `borrow()` inside, something like `present()`

**Option 3:**

```rust
  let tokens = minter_badge.authorize(|badge| {
    token_def.mint(amount, badge)
  });
```

Use the `authorize` block for functions that require a badge

**Comment by iamyulong** [comment]
I would go against Option 1, as it gives me the impression that we're passing the ownership of the badge to the `mint` function.

I like the idea of avoiding using Rust's `borrow()` function, as borrow has special meaning in DeFi application.

The original purpose of Option 3 was to simplify to flow of using badge in a vault for authorization:
1. Take 1 badge from a `Vault`  into a `Bucket`
1. Create a `BucketRef`
1. Pass the `BucketRef` to some function
1. Put the badge back into the original `Vault`

And we later added the same method to `Bucket` for consistency. 

For option 3, I'd like to propose a small variable name change, to reflect the fact that badge is still owned by the caller:
```rust
let tokens = minter_badge.authorize(|auth| {
    token_def.mint(amount, auth)
});
```

Overall, I would like to see both option 2 & 3. If this causes too much burden to a developer, I think we should keep Option 3.

**Comment by kroggen** [comment]
Really good!

The word `badge` many times was a bit confusing indeed, your suggestion nailed it!
