### ISSUE TITLE
Better docs for SmartValue

### ISSUE THREAD

**Issue by dRAT3** [radixdlt/radixdlt-scrypto#57]
It is unclear from the docs that you have to us scrypto_decode::\<T\>(&smart_value.encoded) to use a SmartValue.

**Comment by iamyulong** [comment]
Hi @dRAT3, thanks for raising this up. 

I'm hesitating to provide documentation about `SmartValue` at this comment, as it will likely be replaced with `sbor::Value`. 

For now, you can consider it as any sbor value with the encoding cached for performance.

**Comment by russellharvey** [comment]
Obsolete
