### ISSUE TITLE
Import macro for blueprints is broken is certain cases

### ISSUE THREAD

**Issue by backyard-coder** [radixdlt/radixdlt-scrypto#582]
The import! macro seems to be broken when the ABI contains multiple methods/functions that return the same Struct. Apparently there is a problem with deriving Encode, Decode, etc.

Please see the following file for a reproduction of the problem: https://gist.github.com/backyard-coder/b9f7e5998339fb1080bcca725202ae8b

The problem occurs on branch main (commit 3eb552542efd13f441b8dc78c2ba5d88e1118958).

**Comment by russellharvey** [comment]
Obsolete
