### ISSUE TITLE
Add ability to get current component's address inside methods

### ISSUE THREAD

**Issue by cbisaillon** [radixdlt/radixdlt-scrypto#60]
Would it be possible to add the ability to retrieve the current component's method address from the Context ?

**Comment by iamyulong** [comment]
This is a nice-to-have feature; will add it to our backlog.

**Comment by 0xOmarA** [comment]
Closing this issue as this functionality was added with v0.3.0 of Scrypto and later improved with v0.4.0. As of v0.4.0, you can get the component address through:

```rust
let component_address: ComponentAddress = Runtime::actor().component_address().unwrap();
```
