### ISSUE TITLE
Add ability for badges to hold data

### ISSUE THREAD

**Issue by MiroLiebschner** [radixdlt/radixdlt-scrypto#62]
Badges are a great concept but many of the possible use cases are not yet possible. 
E.g., the "voting power" of a user can not be determined by the badge alone as of now.

Therefore, it would be great of badges could hold values.

**Comment by iamyulong** [comment]
As of now, the default badge implementation is based on fungible resource (no data, but some quantity). Once NFT is in place, we may be able to create badges based on non-fungible resource, which allows metadata for individual unit.

**Comment by 0xOmarA** [comment]
Newer versions of Scrypto support NFTs, so, it's now possible to have badges that have data on them.
