### ISSUE TITLE
Add a LICENSE, CODE_OF_CONDUCT.md, CONTRIBUTING.md

### ISSUE THREAD

**Issue by devmannic** [radixdlt/radixdlt-scrypto#66]
The repository has no license information.  It really should have a declared license ASAP.  The rest are nice to have too.

- [x] add LICENSE (one or more)
- [x] add CODE_OF_CONDUCT.md
- [x] add CONTRIBUTING.md

I know that building a developer community is a high priority for RDX Works (formerly RadixDLT).  IMHO missing these guidelines/declarations runs counter to that goal.  You may also want to check on the other radixdlt organization repositories for similarly missing files.

An obvious choice is the Radix License (radixfoundation.org/licenses/license-v1),  Please consider an equally or more permissive license which is more commonly used for software to be applied at least to the example code if not the entire repository.  I'd suggest one or both of MIT and Apache-2.

Without a license, the Github Terms of Service makes some grants .  However, this does not cover publishing derivative works to any non-GitHub service.

For example, I am working on a library which includes modified versions of these examples and some derived functionality.  I would like to publish the package on crates.io, but without license information here, I really should only include it on GitHub.  It's not a showstopper, but it doesn't feel good.

For reference: excerpt from Github [ToS](https://docs.github.com/en/github/site-policy/github-terms-of-service#5-license-grant-to-other-users) implies the following:

> License Grant to Other Users
> 
> Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be > viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories 
> (this means that others may make their own copies of Content from your repositories in repositories they control).
> 
> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to 
> use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted 
> through GitHub's functionality (for example, through forking). You may grant further rights if you adopt a license. If you are 
> uploading Content you did not create or own, you are responsible for ensuring that the Content you upload is licensed under terms 
> that grant these permissions to other GitHub Users.

**Comment by iamyulong** [comment]
Yes, this is on our TODO list. It should be resolved before Alexandria release.

**Comment by iamyulong** [comment]
Added relative documentation
