### ISSUE TITLE
Confusion when using Decimal::one() in user code

### ISSUE THREAD

**Issue by backyard-coder** [radixdlt/radixdlt-scrypto#67]
I came upon a possible point of confusion while trying to withdraw a single token from a vault. Please consider the two below methods:

```rust
pub fn withdraw_one(&self) ->Bucket {
    let amount :Decimal = 1.into();
    self.vault.take(amount)
}

pub fn withdraw_one_and_be_surprised(&self) -> Bucket {
    let amount :Decimal = Decimal::one();
    self.vault.take(amount)
}
```
At first glimpse both methods seem to be doing the same thing, which is to withdraw one full token (`1.000000000000000000`) from the vault. I would argue, however, that `withdraw_one` behaves as one would expected, while `withdraw_one_and_be_surprised` does not. The later method only returns `0.000000000000000001` tokens.

This is of course not necessarily a bug in itself but it may very well lead to bugs in user code. It sure did get me by surprise and (being new to Rust) - took me longer to figure out than I am proud to admit. It might be useful to rename the constant, so the difference to `1.into()` becomes immediately apparent to users.

**Comment by iamyulong** [comment]
Good idea. Definitely worth adding this convenience method.

**Comment by iamyulong** [comment]
Thank you @devmannic for pointing this out. You're right; I must have misread the issue description before.

Fixing this now...

**Comment by iamyulong** [comment]
Fix merged into develop branch
