### ISSUE TITLE
Encryption on ledger

### ISSUE THREAD

**Issue by Kansuler** [radixdlt/radixdlt-scrypto#74]
It would be useful to be able to encrypt sensitive data that is serialized on the ledger, implemented in a way that only the owner of a badge or NFT can decrypt this information. Is this something that is on the roadmap?

A few top of the head examples of information that could use encryption:

### Personal data
Looking at the [crowdsourcing](https://github.com/radixdlt/community-scrypto/pull/14) example provided in PR to the community repository. Collection of addresses to send rewards to for instance is sensitive data that shouldn't be readable on ledger.

### Escrow
With an escrow contract, there is a possibility that subject of agreement is sensitive and need to be stored encrypted.

**Comment by iamyulong** [comment]
Yep, there is nothing stopping us from storing encrypted data in an NFT unit. You will need to encrypt and decrypt the data off-chain though, which also means we can't have on-chain logic that acts on encrypted data.
