### ISSUE TITLE
Enable static linkage of intra-package blueprints

### ISSUE THREAD

**Issue by devmannic** [radixdlt/radixdlt-scrypto#80]
I'd like to suggest a minor change to the `blueprint!` macro which enables a blueprint to reference another blueprint in the same package *without* the secondary blueprint being instantiated as a separate component at a separate address.

In effect this allows direct use of functionality "vendoring" dependencies.  At least, it's another way to do code reuse with different tradeoffs.

The changes are:
1. make the `blueprint` module's visibility `pub(crate)` so other modules in the create can access it.
    * Purposefully not `pub` because all the the generated code should not be accessible from outside of wasm for this use case. -- An optimization might be to add a new macro for this use case that doesn't generate as much unnecessary code.  This proposal is more pragmatic while much of the code is still in flux I don't think refactoring or duplicating much of the macro code is wise.
2. Make sure `sbor::Describe` is implemented so the secondary blueprint storage can be directly used in fields of the main blueprint storage

The change looks like this:

```diff
diff --git a/scrypto-derive/src/blueprint.rs b/scrypto-derive/src/blueprint.rs
index 3ff9aa6..2932adb 100644
--- a/scrypto-derive/src/blueprint.rs
+++ b/scrypto-derive/src/blueprint.rs
@@ -43,7 +43,7 @@ pub fn handle_blueprint(input: TokenStream) -> Result<TokenStream> {
     }
 
     let output_mod = quote! {
-        mod blueprint {
+        pub(crate) mod blueprint {
             use super::*;
 
             #[derive(::sbor::TypeId, ::sbor::Encode, ::sbor::Decode)]
@@ -452,7 +452,7 @@ fn generate_stubs(bp_ident: &Ident, items: &[ImplItem]) -> Result<TokenStream> {
     }
 
     let output = quote! {
-        #[derive(::sbor::TypeId, ::sbor::Encode, ::sbor::Decode)]
+        #[derive(::sbor::TypeId, ::sbor::Encode, ::sbor::Decode, ::sbor::Describe)]
         pub struct #bp_ident {
             address: ::scrypto::types::Address,
         }

```

And then one blueprint can create the storage struct from another blueprint and everything "just works".  For example:

```rust
mod lib2;
use scrypto::prelude::*;
blueprint! {
    struct Hello {
        // Define what resources and data will be managed by Hello components
        sample_vault: Vault,
        hello2: lib2::blueprint::Hello2,  // using the internal type here
    }
/* ... */
            let c1 = Self {
                sample_vault: Vault::with_bucket(my_bucket),
                hello2: lib2::blueprint::Hello2::new()  // call the internal function here which should return a Hello2, not a Component
            }
/* ... */
            let b2 = self.hello2.free_token2();  // call the function in the exact same way as if it was a Component of type lib2::Hello2
/* ... */
```

The full example is here: https://github.com/devmannic/scrypto-playground/tree/main/hello-crosscall-static

I full PR would include the above changes and some example to test the feature.  The example could be an added rewrite of cross-blueprint-call maybe or just a simple example.

Thanks

**Comment by iamyulong** [comment]
Thank you @devmannic for the suggestion!

I understand that there might be some use cases which require direct access to the blueprint struct, but I'm not feeling comfortable exposing it ATM as this would break abstraction provided by blueprints. The `struct` may not be available in the future.

`Describe` is only required if the data structure is used for public methods (part of the ABI). Adding `Desribe` derive to the blueprint struct would require `Describe` trait for all the fields.

**Comment by devmannic** [comment]
Thanks for the comments.  I agree `Describe` does not seem to be the right choice here.  In light of that I don't see a simple solution.  After reading this I would agree my suggestion is not the right approach at all.  Let's keep this issue open since it's not specific to the final implementation choices though.  I have a few more ideas about Traits which I think are relevant here:

I think in the Rust world this is exactly the use case where traits are the solution.  Using traits for the local/static ABI to enforce interfaces and still get static dispatch seems ideal.  Of course we still need the "real" encode/decode ABI for crossing the ledger/component boundary).  So maybe a solution that consistently uses traits for both is the right answer.  Something like a proc-macro for traits (maybe used indirectly by the blueprint macro) that creates the stubs as they are now for inter-package access and also (somehow) allows intra-package access.  As it is today, one can't `impl Trait` inside a blueprint at all which makes it impossible for the compiler to help verify a blueprint is conforming to some expected interface anyway,  It also makes it harder to leverage some Rust features which is frustrating.  It'd be nice if `impl Trait...` worked at a minimum, and if it was part of the larger design solution for interfacing between blueprints whether that be inter or intra package, I think it would be a nice approach.

---

This is slightly off topic for static linkage, but relevant for intra-package and inter-package cross blueprint calls and related to the Traits ideas above.  We may want to move it to another discussion about inter-blueprint calls that are explicitly NOT static, but I'll get the thoughts here because they are relevant for a general implementation of cross-blueprint calls.

At the moment I don't think there's a way to define an interface to a component who's package is unknown at compile time.  At least not an obvious, efficient way.  Basically we don't have a way to "virtually" call a Component using something like duck typing.   Building on Rust's traits could be perfect for this IMHO, and could provide a consent single strategy to deal with static linkage too.  I don't think it's a straight forward implementation though.

I've tried to approximate this in an example I'm writing where one component calls another by address and just needs to know 2 methods exist without being constrained to a specific blueprint (and storage layout) (exactly the case for Traits).  I have not found a way to do this..  I think I know how it could be done, but I don't think the blueprint macro generates the right structs/functions to make this possible today.  Any insights on this related (but different) use case?

**Comment by russellharvey** [comment]
Happy with latest way of achieving something like this.
