### ISSUE TITLE
Unable to change the library name to anything other than `out`

### ISSUE THREAD

**Issue by plymth** [radixdlt/radixdlt-scrypto#94]
It seems we don't have the flexibility to change the lib name inside the Cargo.toml file. Changing it to anything other than `out` causes issues with testing and compiling.  Also when docs are generated, they are labelled as `out ` too.

Would it be possible to update the following code to allow the lib name to default to maybe `CARGO_BIN_NAME ` to we can at least define a name we would like.

I believe this is the location of the file that needs to be updated:
https://github.com/radixdlt/radixdlt-scrypto/blob/ce6b70929bf487a2cc6779133ddbbc1981893624/scrypto/src/lib.rs

I think we can do something like the following:

```rust
#[macro_export]
macro_rules! include_code {
    () => {
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            format!("/target/wasm32-unknown-unknown/release/{}.wasm", env!("CARGO_BIN_NAME") )
        ))
    };
    ($package_dir: expr) => {
        include_bytes!(concat!(
            $package_dir,
            format!("/target/wasm32-unknown-unknown/release/{}.wasm", env!("CARGO_BIN_NAME"))
        ))
    };
}
```

**Comment by iamyulong** [comment]
Thank you @plymth for the suggestion! I will test the proposed change and make a PR if nothing breaks.

**Comment by iamyulong** [comment]
Hi there, I did a quick try with `CARGO_BIN_NAME`. It's not defined for a library (which is the case for Scrypto). I will explore if there is a better solution later.

**Comment by plymth** [comment]
@iamyulong or maybe you can use `CARGO_PKG_NAME `

**Comment by iamyulong** [comment]
We were using `CARGO_PKG_NAME` [before](https://github.com/radixdlt/radixdlt-scrypto/commit/a0996b6a8a45c469d484d2bc219cd4617d109662). It doesn't handle hyphen-underscore properly, if we insist on compile-time wasm path construction. There might be other clever options, which I will explore after Alexandria release.

**Comment by plymth** [comment]
@iamyulong no worries then, thanks for looking into it 🙂

**Comment by plymth** [comment]
@devmannic didn't realise you could tap into `replace` from an environment variable, that's pretty neat 😁

**Comment by iamyulong** [comment]
Changes merged:
- `include_code!` now takes an additional parameter for library name. 
- `resim publish` automatically resolve the library name from the Cargo Manifest file.
